vsync = true;
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;

###########
# opacity #
###########
#
frame-opacity = 1;
inactive-opacity = 1;
active-opacity = 1;
inactive-opacity-override = false;
opacity-rule = [
	"99:window_type = 'dock'",
    "100:class_i = 'i3-frame'",
	"97:class_g = 'org.wezfurlong.wezterm' && focused",
	"80:class_g = 'org.wezfurlong.wezterm' && !focused",
	"97:class_g = 'Code' && focused",
	"80:class_g = 'Code' && !focused",
	"97:class_g = 'VSCodium' && focused",
	"80:class_g = 'VSCodium' && !focused",
	"98:class_g = 'jetbrains-studio' && focused",
	"70:class_g = 'jetbrains-studio' && !focused"
]

#################
# corner radius #
#################

corner-radius = 12;
# rounded-corners-exclude = [
#     "window_type = 'dock'"
# ];
corner-radius-rules = [ 
	"8:class_i = 'i3-frame'",
    "8:class_i = 'i3bar'",
	"10:window_type = 'popup_menu'",
	"10:window_type = 'dropdown_menu'",
	"10:window_type = 'menu'",
    "0:window_type = 'dock'"
];   


##########
# fading #
##########

fading = true;
fade-delta = 3;
no-fading-openclose = false;

fade-exclude = [ ];

###########
# shadows #
###########

shadow = true;
shadow-radius = 12;
shadow-opacity = 0.55;
shadow-offset-x = -6;
shadow-offset-y = -6;

########
# blur #
########

blur-background = true;
blur-method = "dual_kawase";
blur-strength = 3;
