backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;

frame-opacity = 1;
inactive-opacity = 1;
active-opacity = 1;
inactive-opacity-override = false;
opacity-rule = [
	"100:window_type = 'dock'",
    "100:class_i = 'i3-frame'",
	"97:class_g = 'org.wezfurlong.wezterm' && focused",
	"80:class_g = 'org.wezfurlong.wezterm' && !focused",
	"97:class_g = 'code' && focused",
	"80:class_g = 'code' && !focused",
	"97:class_g = 'Code' && focused",
	"80:class_g = 'Code' && !focused",
	"98:class_g = 'jetbrains-studio' && focused",
	"70:class_g = 'jetbrains-studio' && !focused"
]

corner-radius = 12;
rounded-corners-exclude = [
    "window_type = 'dock'"
];
corner-radius-rules = [ 
	"8:class_i = 'i3-frame'",
    "8:class_i = 'i3bar'"
];   

# blur-background = true;
# blur-background-exclude = [
# 	"window_type = 'dock'",
# 	"class_g = 'slop'",
# 	"class_g = 'maim'"
# ];

# blur-method = "dual_kawase";
# blur-strength = 5;
# blur: {
#   method = "dual_kawase";
#   strength = 5;
#   background = false;
#   background-frame = false;
#   background-fixed = false;
# }

fading = false;
fade-delta = 2;
no-fading-openclose = false;

fade-exclude = [ ];

vsync = true;
