gesture swipe right xdotool key alt+Left
gesture swipe left xdotool key alt+Right
# gesture swipe down xdotool key alt+ctrl+Right
# gesture swipe up xdotool key alt+ctrl+Left
gesture pinch in 4 /home/$USER/.config/scripts/lock
# gesture swipe up   bash -c 'amixer -q sset Master 5%+ && pkill -RTMIN+1 i3blocks'
# gesture swipe down bash -c 'amixer -q sset Master 5%- && pkill -RTMIN+1 i3blocks'
gesture swipe up playerctl play-pause
gesture swipe down playerctl play-pause
