gesture swipe right bash -c 'xdotool getactivewindow getwindowname | grep -qiE brave && xdotool key alt+ctrl+shift+l'
gesture swipe left bash -c 'xdotool getactivewindow getwindowname | grep -qiE brave && xdotool key alt+ctrl+shift+h'
gesture pinch in 3 /home/$USER/.config/scripts/lock
# gesture swipe up   bash -c 'amixer -q sset Master 5%+ && pkill -RTMIN+1 i3blocks'
# gesture swipe down bash -c 'amixer -q sset Master 5%- && pkill -RTMIN+1 i3blocks'
