# do not stow to home dir, stow to /etc/keyd
[ids]

*

[main]
# hold space - homerow becomes vim navigation
# (while holding space):
# press capslock - toggle between navigation and numbers/symbols
capslock = esc
rightshift = layer(symbols)
leftalt = overload(alt, oneshot(toggle_space_mode))
rightalt = overload(alt, capslock)
space = overloadt(main_nav, space, 190)
esc = timeout(layer(change_layout), 80, esc)

[toggle_space_mode]
leftalt = overload(alt, toggle(space_mode))

[change_layout]
1 = toggle(normal)
2 = toggle(colemak)

[normal]
capslock = capslock
rightshift = rightshift
leftshift = leftshift
space = space
rightalt = rightalt
leftalt = leftalt

# esc = overload(reset, esc)
esc = timeout(layer(reset), 100, esc)

[colemak]
w = w
, = ,
s = r
a = a
c = c
g = d
q = q
e = f
] = ]
d = s
/ = /
; = o
' = '
r = p
f = t
t = g
u = l
. = .
j = n
k = e
p = ;
o = y
z = z
h = h
i = u
[ = [
v = v
l = i
m = m
n = k
x = x
b = b
y = j
space = overloadt(colemak_nav, space, 190)

[space_mode]
space = space 

[symbols:S]
capslock = capslock

[main_numbers]
a = 1
s = 2
d = 3
f = 4
g = 5
h = 6
j = 7
k = 8
l = 9
; = 0
q = !
w = @
e = #
r = $
t = %
y = ^
u = &
i = *
o = (
p = )
v = =
b = -
n = _
m = +
' = `
c = ~
capslock = swap(main_nav)
# capslock = overload(shift, swap(main_nav))

[main_nav]
h = left
j = down
k = up
l = right
w = C-right
b = C-left
u = C-z
r = C-y
d = C-x
y = C-c
p = C-v
x = backspace
( = home
) = end
[ = pageup
] = pagedown
leftshift = layer(word_del)
#backspace = C-backspace
capslock = swap(main_numbers)
# capslock = overload(shift, swap(main_numbers))

[word_del:S]
backspace = C-backspace

[colemak_nav]
h = left
y = down
n = up
u = right
w = C-right
b = C-left
i = C-z
s = C-y
g = C-x
o = C-c
r = C-v
x = backspace
( = home
) = end
[ = pageup
] = pagedown
leftshift = layer(word_del)
# backspace = C-backspace
capslock = swap(colemak_numbers)
# capslock = overload(shift, swap(colemak_numbers))

[colemak_numbers]
a = 1
s = 2
d = 3
f = 4
g = 5
h = 6
j = 7
k = 8
l = 9
; = 0
q = !
w = @
e = #
r = $
t = %
y = ^
u = &
i = *
o = (
p = )
v = =
b = -
n = _
m = +
' = `
c = ~
capslock = swap(colemak_nav)
# capslock = overload(shift, swap(colemak_nav))
